export const REDUCEPRODUCTS = [
  {
    id: 0,
    title: "Bamboo Toothbrush",
    price: "€5",
    description: "Duis iaculis magna mi, a interdum ligula congue ac. Aliquam pulvinar mollis eleifend. Suspendisse a mollis orci. ",
    src: "/assets/images/toothbrush.jpg",
    site: "https://thebamandboo.com/pages/all-products",
  },
  {
    id: 1,
    title: "Recycled Cast Iron Pan",
    price: "€90",
    description: "Duis iaculis magna mi, a interdum ligula congue ac. Aliquam pulvinar mollis eleifend. Suspendisse a mollis orci.",
    src: "/assets/images/skillet.jpg",
    site: "https://uk.buymeonce.com/products/recycled-cast-iron-frying-pan-28cm?_pos=16&_sid=00d0266bf&_ss=r",
  },
  {
    id: 2,
    title: "Complete Knife Set",
    price: "€165",
    description: "Duis iaculis magna mi, a interdum ligula congue ac. Aliquam pulvinar mollis eleifend. Suspendisse a mollis orci.",
    src: "/assets/images/knife.jpg",
    site: "https://uk.buymeonce.com/products/furi-set-3?_pos=1&_sid=56b73ba35&_ss=r",
  },
  {
    id: 3,
    title: "Delta Shopping Bag",
    price: "€39",
    description: "Duis iaculis magna mi, a interdum ligula congue ac. Aliquam pulvinar mollis eleifend. Suspendisse a mollis orci.",
    src: "/assets/images/bag.jpg",
    site: "https://demano.net/en/50-shopping-bags",
  },
  {
    id: 4,
    title: "Ultra-Reliable Smartphone",
    price: "€255",
    description: "Duis iaculis magna mi, a interdum ligula congue ac. Aliquam pulvinar mollis eleifend. Suspendisse a mollis orci.",
    src: "/assets/images/phone.jpg",
    site: "https://uk.buymeonce.com/products/teracube-2e-ultra-reliable-smartphone?_pos=1&_psq=smartphone&_ss=e&_v=1.0",
  },
  {
    id: 5,
    title: "Stereo Headphones",
    price: "€160",
    description: "Duis iaculis magna mi, a interdum ligula congue ac. Aliquam pulvinar mollis eleifend. Suspendisse a mollis orci.",
    src: "/assets/images/headphones.jpg",
    site: "https://uk.buymeonce.com/products/aiaiai-tma-2-modular-bluetooth-headphones-move-xe-wireless?_pos=6&_sid=720bc59d9&_ss=r",
  },
];
